services:
  oauth2-proxy:
    environment:
      OAUTH2_PROXY_UPSTREAMS: http://fastapi:8000
    depends_on:
      fastapi:
        condition: service_started
  fastapi:
    build:
      context: fastapi
      dockerfile: Containerfile
      target: env
    volumes:
      - ./fastapi/:/app
    env_file: app.env
    depends_on:
      keycloak:
        condition: service_healthy
