services:
  oauth2-proxy:
    environment:
      OAUTH2_PROXY_UPSTREAMS: http://flask:8000
    depends_on:
      flask:
        condition: service_started
  flask:
    build:
      context: flask
      dockerfile: Containerfile
      target: env
    volumes:
      - ./flask/:/app
    env_file: app.env
    depends_on:
      keycloak:
        condition: service_healthy
