FROM docker.io/python:3.11 as env

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

ENV FLASK_RUN_PORT=8000
ENV FLASK_RUN_HOST="0.0.0.0"

CMD flask run

# FROM env as app

# COPY . .
